language: rust
dist: bionic
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo

# Run the script on stable, beta and nightly channels
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script: |
  rustup component add clippy
  cargo install --force cargo-audit
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi

script:
  # see https://rustsec.org/
  - cargo audit
  # fail when encountering warnings on stable or beta
  - cargo clippy -- -D warnings
  # run tests
  - cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
