REGISTRY=${DOCKER_REGISTRY}

TEST_SERVICE_IMAGE_NAME=soda/test-service
TEST_SERVICE_IMAGE_VERSION=0.1.0

build:
	docker build -t soda/test-service .

tag: build
	docker tag $(TEST_SERVICE_IMAGE_NAME) $(REGISTRY)/$(TEST_SERVICE_IMAGE_NAME):$(TEST_SERVICE_IMAGE_VERSION)

push: tag
	docker push $(REGISTRY)/$(TEST_SERVICE_IMAGE_NAME):$(TEST_SERVICE_IMAGE_VERSION)
