REGISTRY=${DOCKER_REGISTRY}

TEST_SERVICE_IMAGE_NAME=soda/test-service
TEST_SERVICE_IMAGE_VERSION=0.2.0
DOCKER_REGISTRY=449410177519.dkr.ecr.eu-west-1.amazonaws.com

build:
	docker build -t $(TEST_SERVICE_IMAGE_NAME) .

tag: build
	docker tag $(TEST_SERVICE_IMAGE_NAME) $(REGISTRY)/$(TEST_SERVICE_IMAGE_NAME):$(TEST_SERVICE_IMAGE_VERSION)

push: tag
	docker push $(REGISTRY)/$(TEST_SERVICE_IMAGE_NAME):$(TEST_SERVICE_IMAGE_VERSION)
